name: docker_publish

on:
  push:
    branches:
      - 'main'
      - 'hiep/support-private-repo'
    tags:
      - '*'

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@v0.4.0
    secrets: inherit
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-lint: true
      run-build: true
      go-private-repos-authentication: true

  docker_pipeline:
    needs: ["lint_test"]
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.4.0
    secrets: inherit
    with:
      publish: true
      go-private-repos-authentication: true
